# 에러 테스트

디버거

[https://mswjs.io/docs/runbook/](https://mswjs.io/docs/runbook/)

테스트를 위해 강제적으로 에러를 발생시키는 작업은 테스트 시나리오 중에서 예외 처리 및 에러 상황에 대한 애플리케이션의 올바른 동작을 확인하는 데 중요합니다. 특정 핸들러에서 강제적으로 에러를 발생시켜 테스트하는 방법은 다음과 같이 작성될 수 있습니다.

1. **`server.resetHandlers`**를 사용하여 MSW(Mock Service Worker)의 서버 핸들러를 재설정합니다.
2. **`http.get`**을 통해 **`http://localhost:3030/scoops`**와 **`http://localhost:3030/toppings`** 엔드포인트에 대한 핸들러를 설정합니다.
3. 위에서 설정한 핸들러는 각각 500 상태 코드를 반환하도록 구성되어 있습니다. 즉, 해당 엔드포인트에 요청이 오면 서버는 500 Internal Server Error를 반환합니다.
4. **`render`** 함수를 사용하여 **`<OrderEntry />`** 컴포넌트를 렌더링합니다.
5. **`screen.findAllByText`**를 통해 화면에 "An unexpected error occurred. Please try again later." 텍스트를 포함한 알림을 찾습니다.
6. **`expect(alerts).toHaveLength(2);`**는 두 개의 알림이 표시되는지 확인하는 테스트입니다.
7. 마지막으로 **`logRoles(container);`**는 컨테이너 내의 역할(role) 정보를 콘솔에 로그하는 작업을 수행합니다.

```tsx
import { HttpResponse, http } from "msw";
import { server } from "../../../mocks/server";

import { logRoles, render, screen } from "@testing-library/react";
import OrderEntry from "../OrderEntry";
import { expect } from "vitest";

test("handler 에러 테스트 scoops과 toppings 엔드포인트일때", async () => {
  server.resetHandlers(
    http.get("http://localhost:3030/scoops"),
    () => {
      return new HttpResponse(null, { status: 500 });
    },
    http.get("http://localhost:3030/toppings"),
    () => {
      return new HttpResponse(null, { status: 500 });
    }
  );

  const { container } = render(<OrderEntry />);

  const alerts = await screen.findAllByText(
    "An unexpected error occurred. Please try again later."
  );
  expect(alerts).toHaveLength(2);

  logRoles(container);
});
```

이 테스트의 목적은 **`OrderEntry`** 컴포넌트가 **`scoops`**와 **`toppings`** 엔드포인트에서 예상치 못한 에러가 발생했을 때, 화면에 에러 메시지가 나타나는지를 확인하는 것입니다. 해당 코드는 MSW를 사용하여 서버의 핸들러를 설정하여 에러 상황을 시뮬레이션하고, 이에 대한 애플리케이션의 올바른 동작을 테스트하는 예시입니다.